export const CHANGE_CUSTOM_REQUEST = 'CHANGE_CUSTOM_REQUEST';
export const CHANGE_CUSTOM_SUCCESS = 'CHANGE_CUSTOM_SUCCESS';
export const CHANGE_CUSTOM_FAIL = 'CHANGE_CUSTOM_FAIL';

export const GET_CUSTOM_REQUEST = 'GET_CUSTOM_REQUEST';
export const GET_CUSTOM_SUCCESS = 'GET_CUSTOM_SUCCESS';
export const GET_CUSTOM_FAIL = 'GET_CUSTOM_FAIL';